# CS111 Lecture 3 - Demo #1
## Spring 2023, Z. Matni

### Basic and Special Matrices in `numpy`
    * Matrix multiplication using the @ operator.
    * Creating random number matrices.
    * Solving for vector x in the Ax = b problem.
    * Finding the residual error and the relative norm of the residual error.
    * Identity, Diagonal, Permutation Matrices.

<em>We'll start off by importing numpy and the linear algebra class (linalg) from numpy</em>

In [18]:
import numpy as np
import numpy.linalg as npla

<em>Let's define a matrix in Python!!</em> 

Ok... a vector, really...

In [19]:
A = np.array([1,2,3])
print(A)

[1 2 3]


<em>Let's do another one!!!!!!</em>

In [20]:
A = np.array([  [1,2,3], [4,5,6], [7,8,9], [10, 11, -12]  ])
print(A)

[[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11 -12]]


## Multiplying 2 matrices

*Let's define 2 4x4 arrays: U and L, and then we'll multiply them as: A1 = LU*

*Note that this is the same example we did in lecture (on the slides)*

*Also, is it the same as A2 = UL?*

In [21]:
# Example of an upper triangular matrix

U = np.array([[2,7,1,8],[0,2,8,1],[0,0,8,2],[0,0,0,8]])
print(U)

[[2 7 1 8]
 [0 2 8 1]
 [0 0 8 2]
 [0 0 0 8]]


In [22]:
# Example of a unit lower triangular matrix

L = np.array([[1,0,0,0],[.5,1,0,0],[0,.5,1,0],[-.5,-.5,0,1]])
print(L)

[[ 1.   0.   0.   0. ]
 [ 0.5  1.   0.   0. ]
 [ 0.   0.5  1.   0. ]
 [-0.5 -0.5  0.   1. ]]


*Ok, we've defined U and L, now let's multiply them (as L.U) and see what we get...*

In [23]:
# The @ operator is matrix multiplication
A1 = L @ U
print(A1)

[[ 2.   7.   1.   8. ]
 [ 1.   5.5  8.5  5. ]
 [ 0.   1.  12.   2.5]
 [-1.  -4.5 -4.5  3.5]]


In [24]:
# Is it the same as A = UL?
A2 = U @ L
print(A2)

[[ 1.5  3.5  1.   8. ]
 [ 0.5  5.5  8.   1. ]
 [-1.   3.   8.   2. ]
 [-4.  -4.   0.   8. ]]


## Creating random number matrices

***np.random.rand(N)*** *creates a set of N random numbers in one row*

***np.round()*** *rounds up the numbers to the nearest integer (how could we make them round up to, say the 2nd decimal?)*

In [25]:
A = 10 * np.random.rand(5)
A= A.T
print(A)

[6.36008958 3.54069368 0.24192389 7.62940572 8.59280931]


In [26]:
print(np.round(A))

[6. 4. 0. 8. 9.]


In [27]:
# Note the use of .round() and .rand()

MyX = np.round( 10 * np.random.rand(5) )
print(MyX)

[ 5.  6. 10.  1.  2.]


In [28]:
print(A@MyX)

80.27887318323451


In [29]:
#TEst
X = 10 * np.random.rand(5)
Y = np.array([[1],[1]])
print(X @ Y)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 5)

*Let's try to find the matrix multiplication of A.MyX*

***What limitations do I have?***

In [30]:
A = np.array([[1, 2], [3, 4]])
MyX = np.round( 10 * np.random.rand(2) )

# @ operator: matrix multiplication
b = A @ MyX
print(b)

[15. 31.]


*Instead of what we did above, I will ask numpy to just solve **x** for **Ax = b** for me using the **np.solve()** function.*

This is **exactly** the 3x3 matrix example we did in class! - Recall that the solution was **(-1, 1.5, 1)**

In [31]:
A = np.array([[1,0,2],[2,2,0],[3,2,1]])
print(A, "\n")

b = np.array([1,1,1])
print(b)

[[1 0 2]
 [2 2 0]
 [3 2 1]] 

[1 1 1]


**I am now going to solve for vector x where: Ax = b**

Notice that I didn't force **b** to be a *column* and that the following code works fine if **b** is defined as a *row*

In [32]:
# Use the solve() function from npla (np.linalg)
# This solves for x in Ax = b setup

X = npla.solve(A, b)
#solves via gaussian elimination 
print(X)

[-1.   1.5  1. ]


Another example!

In [33]:
# Creating a right-hand side for which we know the answer to Ax=b

A = 20*np.random.rand(5,5)
#Creates a 5 by 5 matrix
xorig = np.round(10*np.random.rand(5))
print("A:\n", A)
print("\noriginal x:\n", xorig)
b = A @ xorig
print("\nright-hand side b:\n", b)

A:
 [[14.99684498 14.64928596  3.86418305 15.4210709  13.59961875]
 [ 8.15838042 15.30988526 14.07357229  6.44925497  2.73958087]
 [ 5.70712276  0.73838734 11.06643504 16.98664824  3.39429629]
 [18.65148375 17.30397133  0.76632911 19.94933675 15.68070339]
 [15.44532137 12.22352477  9.36285712  0.51819185 18.20877774]]

original x:
 [2. 6. 0. 9. 2.]

right-hand side b:
 [283.87828129 171.69852891 175.51299625 352.03223303 145.31307346]


*Now*, let's just give Python **A** and **b** and ask it to solve for **x** where **Ax = b**.

Let's then compare what it calculates vs. our own given **x** vector from the previous code above.

In [34]:
x = npla.solve(A,b)
print("computed x:", x)

computed x: [2. 6. 0. 9. 2.]


So, ARE the *original x* and the *computed x* ***exactly*** the same?

In [35]:
residual = b - A@x
print("residual:", residual)
print("relative norm of residual:", npla.norm(residual) / npla.norm(b))

residual: [ 0.00000000e+00 -2.84217094e-14 -2.84217094e-14 -5.68434189e-14
 -2.84217094e-14]
relative norm of residual: 1.4063098055416362e-16


*Demonstrating the range() method*

Python can create an integer range from 0 to N-1, in steps of 1, with the term **range(N)**:

In [36]:
np.array(range(25))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

We can also "reshape" this vector into a MxN matrix of our choosing:

In [37]:
import numpy as np
print(np.array(range(30)).reshape(5,6) )  # Gives us a 5x5 matrix

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


Demonstrating how to create the identity matrix, **I**

In [38]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


What is the answer to the matrix multiplication AI ?? Is it the same as IA?

### Special Matrices in Python!

**IDENTITY MATRIX**

In [39]:
# Identity matrix
I = np.eye(5)
print(I)
print(A)
print(A@I)
residual = A - A@I
print(residual)
print(I@A == A@I)
print(npla.norm(A@I - I@A))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[14.99684498 14.64928596  3.86418305 15.4210709  13.59961875]
 [ 8.15838042 15.30988526 14.07357229  6.44925497  2.73958087]
 [ 5.70712276  0.73838734 11.06643504 16.98664824  3.39429629]
 [18.65148375 17.30397133  0.76632911 19.94933675 15.68070339]
 [15.44532137 12.22352477  9.36285712  0.51819185 18.20877774]]
[[14.99684498 14.64928596  3.86418305 15.4210709  13.59961875]
 [ 8.15838042 15.30988526 14.07357229  6.44925497  2.73958087]
 [ 5.70712276  0.73838734 11.06643504 16.98664824  3.39429629]
 [18.65148375 17.30397133  0.76632911 19.94933675 15.68070339]
 [15.44532137 12.22352477  9.36285712  0.51819185 18.20877774]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
0.0


In [42]:
print(A@I)
print('\n', I@A)
print(np.all(A@I))
print(np.all(np.array([[1,0,1],[1,1,1],[1,1,1]])))
print(np.all(A@I == I@A))

[[14.99684498 14.64928596  3.86418305 15.4210709  13.59961875]
 [ 8.15838042 15.30988526 14.07357229  6.44925497  2.73958087]
 [ 5.70712276  0.73838734 11.06643504 16.98664824  3.39429629]
 [18.65148375 17.30397133  0.76632911 19.94933675 15.68070339]
 [15.44532137 12.22352477  9.36285712  0.51819185 18.20877774]]

 [[14.99684498 14.64928596  3.86418305 15.4210709  13.59961875]
 [ 8.15838042 15.30988526 14.07357229  6.44925497  2.73958087]
 [ 5.70712276  0.73838734 11.06643504 16.98664824  3.39429629]
 [18.65148375 17.30397133  0.76632911 19.94933675 15.68070339]
 [15.44532137 12.22352477  9.36285712  0.51819185 18.20877774]]
True
False
True


**DIAGONAL MATRIX**

Notice: What does **A.D** do compared with **D.A** ??

In [43]:
D = np.diag([2,1,1,0,3])
print(D)

[[2 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 3]]


In [44]:
A = np.array(range(25)).reshape(5,5)

print(A, '\n')
print(A@D, '\n')
print(D@A, '\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  1  2  0 12]
 [10  6  7  0 27]
 [20 11 12  0 42]
 [30 16 17  0 57]
 [40 21 22  0 72]] 

[[ 0  2  4  6  8]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  0  0  0  0]
 [60 63 66 69 72]] 



In [46]:
A = np.array(range(25)).reshape(5,5)
print(A, '\n')
A[3,4] = 99
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 99]
 [20 21 22 23 24]]


## Presenting different parts of a matrix

### MANIPULATION of ROWS and COLUMNS of a matrix in Python

****These are important to know how to do!!!****

In [ ]:
# Show the size of a matrix

A = np.array([
    [ 2. ,  7. ,  1. ,  8. ],
    [ 1. ,  5.5,  8.5,  5. ],
    [ 0. ,  1. , 12. ,  2.5],
    [-1. , -4.5, -4.5,  3.5]])

print(A.shape)

(4, 4)


In [47]:
# Single element that's in row 2, column 1

print(A[2, 1])
print(A[2][1])

11
11


In [ ]:
# Show all rows up to, but not including, row 2

print(A[ : 2])

[[2.  7.  1.  8. ]
 [1.  5.5 8.5 5. ]]


In [ ]:
# Show all rows starting from row 2 up until the end

print(A[2 : ])

[[ 0.   1.  12.   2.5]
 [-1.  -4.5 -4.5  3.5]]


In [ ]:
# Show rows in some range [a:b], which means start at a, end at just before b
# aka  [a, b) in mathematical language...

print(A[1 : 3])

[[ 1.   5.5  8.5  5. ]
 [ 0.   1.  12.   2.5]]


In [ ]:
# General: show row n and all columns of it

print(A[2, :])

[ 0.   1.  12.   2.5]


In [51]:
# General: show column m and all rows of it
print(A)
print(A[:, 2])
print(A[:,1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 99]
 [20 21 22 23 24]]
[ 2  7 12 17 22]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


In [ ]:
# Show some range of rows, some range of columns:

print( A[ 1:3, 1:3] ) 


[[ 5.5  8.5]
 [ 1.  12. ]]


### Demonstrating how to change the row, column order in a matrix

In [57]:
# Changing the row order by using an 'indexed' permutation vector
A = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
B = A[ [1,0,2,3] , :]
print("A =\n", A, '\n')
print("B =\n", B, '\n')

A =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

B =
 [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]
 [13 14 15 16]] 



In [ ]:
# Changing the column order
B = A[:, [1,0,2,3]]
print("A =\n", A, '\n')
print("B =\n", B, '\n')

A =
 [[ 2.   7.   1.   8. ]
 [ 1.   5.5  8.5  5. ]
 [ 0.   1.  12.   2.5]
 [-1.  -4.5 -4.5  3.5]] 

B =
 [[ 7.   2.   1.   8. ]
 [ 5.5  1.   8.5  5. ]
 [ 1.   0.  12.   2.5]
 [-4.5 -1.  -4.5  3.5]] 



**PERMUTATION MATRIX**

*Demonstrating the .permutation() function and its use in rearraning row order in a matrix*

In [61]:
A = np.array(range(25)).reshape(5,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [62]:
P = np.array([[1,0,0,0,0], [0,0,0,0,1], [0,0,1,0,0], [0,1,0,0,0], [0,0,0,1,0]])
print(P)

# P is called a Permutation Matrix

[[1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]]


In [63]:
print(A@P, '\n')
print(P@A)

[[ 0  3  2  4  1]
 [ 5  8  7  9  6]
 [10 13 12 14 11]
 [15 18 17 19 16]
 [20 23 22 24 21]] 

[[ 0  1  2  3  4]
 [20 21 22 23 24]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [ ]:
# Create a 'indexed' permutation vector

P = np.random.permutation(5)
print(P)

[0 2 3 1 4]


In [ ]:
vec = np.random.permutation(5)
I = np.eye(5)

print(vec, "\n")
P1 = I[vec, :]
print(P1, '\n')

P2 = I[:, vec]
print(P2)


[2 0 4 1 3] 

[[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]] 

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]


**TRANSPOSE operation**

In [ ]:
print(A, '\n')

# Transpose of A   A^T
print(A.T)

### Inverse Matricies

In [65]:
# Matrix A as shown in the lecture
A = np.array([[2, -1], [-1, 2]])
print(A)

[[ 2 -1]
 [-1  2]]


**Remember:** If the det(A) is zero, then you cannot find an inverse matrix A^-1

In [66]:
detA = npla.det(A)
print(detA)

2.9999999999999996


In [67]:
Ainv = npla.inv(A)
print("Inverse of matrix A =\n", Ainv)

Inverse of matrix A =
 [[0.66666667 0.33333333]
 [0.33333333 0.66666667]]


*Let's verify that that is indeed the inverse of matrix A* by multiplying AA^-1 (what do we expect??)

In [68]:
print( A@Ainv, "\n\n" )
print( Ainv@A )

[[1. 0.]
 [0. 1.]] 


[[1. 0.]
 [0. 1.]]


*That checks out... Now, let's look at another matrix B...*

In [69]:
# What's the deal with matrix B?!
B = np.array([[2, -1], [-2, 1]])
print(B, "\n")

detB = npla.det(B)
print("det(B) = ", detB)

[[ 2 -1]
 [-2  1]] 

det(B) =  0.0


*Since the determinate of B came out to be zero, it means B is a **singular** matrix*

Singular matrices cannot be inverted.

In [70]:
Binv = npla.inv(B)

LinAlgError: Singular matrix

*What about these 2 matrix examples?*

In [71]:
M = np.array( [ [1, -1, 2], [2, 1, 0], [-3, 3, -6] ] )
M = np.array( [ [1, 0, 1], [2, 1, 1], [4, 3, 1] ] )

print(M, '\n')
detM = npla.det(M)
print(detM)
print(npla.matrix_rank(M))

[[1 0 1]
 [2 1 1]
 [4 3 1]] 

0.0
2
