# CS111 Lecture 3 - Demo #2
## Spring 2023, Z. Matni

## `A = LU` Factorization

### Again, we'll start off by importing numpy and the linear algebra class (linalg) from numpy

In [1]:
import numpy as np
import numpy.linalg as npla

### LU Factorization
*Consider a SQUARE 4x4 matrix A as shown in lecture...*

In [2]:
A = np.array([
    [ 2. ,  7. ,  1. ,  8. ],
    [ 1. ,  5.5,  8.5,  5. ],
    [ 0. ,  1. , 12. ,  2.5],
    [-1. , -4.5, -4.5,  3.5]])
print("A =\n", A,'\n')

A =
 [[ 2.   7.   1.   8. ]
 [ 1.   5.5  8.5  5. ]
 [ 0.   1.  12.   2.5]
 [-1.  -4.5 -4.5  3.5]] 



*Recall we found U and L in the exercise we did in lecture.*

We used Gaussian elimination on the blackboard to triangularize A, giving us the matrix U.

During Gaussian elimination, we wrote down the multipliers in a lower triangular array,
then put ones on the diagonal, giving us L.

L and U were found to be:

In [3]:
U = np.array([[2,7,1,8],[0,2,8,1],[0,0,8,2],[0,0,0,8]])
L = np.array([[1,0,0,0],[.5,1,0,0],[0,.5,1,0],[-.5,-.5,0,1]])
print("U =\n", U, "\n\nL=\n", L)

U =
 [[2 7 1 8]
 [0 2 8 1]
 [0 0 8 2]
 [0 0 0 8]] 

L=
 [[ 1.   0.   0.   0. ]
 [ 0.5  1.   0.   0. ]
 [ 0.   0.5  1.   0. ]
 [-0.5 -0.5  0.   1. ]]


#### Let's see if that works...

In [4]:
import numpy.linalg as npla
print("L.U:\n", L @ U)
print()
print("vs. original A:\n", A)
print("np.residual norm", npla.norm(A - L@U))

L.U:
 [[ 2.   7.   1.   8. ]
 [ 1.   5.5  8.5  5. ]
 [ 0.   1.  12.   2.5]
 [-1.  -4.5 -4.5  3.5]]

vs. original A:
 [[ 2.   7.   1.   8. ]
 [ 1.   5.5  8.5  5. ]
 [ 0.   1.  12.   2.5]
 [-1.  -4.5 -4.5  3.5]]
np.residual norm 0.0


#### Just HOW different are these 2 results (LU vs A)???
#### Are there any "residuals"???

In [5]:
# The "residual" is the difference:
print("residual:\n", L@U - A)

# If we want to "boil" this down to a single scalar number AND compare it to the "original",
# then, we want to find the "RELATIVE RESIDUAL" value:
print("rel.norm of res.:\n", npla.norm(L@U - A)/npla.norm(A))

residual:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
rel.norm of res.:
 0.0


*Note how "clean" the residual is (i.e. it's exactly 0)*
#### So... They're exactly the same!

## LU FACTORIZATION
### Create a function to automate this factorization technique
**Create a function LUfactorNoPiv() that will take in a matrix A and return its L and U factors**

*The NoPiv is for "no pivoting needed" - we'll cover that AFTER we figure this one out...*

In [6]:
def LUfactorNoPiv(A):
    """Factor a square matrix, A == L @ U (no partial pivoting)
    Parameters: 
      A: the matrix.
    Outputs (in order):
      L: the lower triangular factor, same dimensions as A, with ones on the diagonal
      U: the upper triangular factor, same dimensions as A
    """
    
    # Check the input - matrix A has to be square
    m, n = A.shape
    assert m == n, 'input matrix A must be square'
    
    # Make a copy of the matrix that we will transform into L and U
    # This is to ensure we can operate with floating-point numbers 
    # deep copy, set type to 64 bit floating point numbers
    LU = A.astype(np.float64).copy()
    
    # Go through the algorithm:
    # Eliminate each column in turn

    #Start at 0 go to n - 1
    #If went to (1,5) will go to 1234, (1,5,2) step of each for loop -> 13
    for piv_col in range(n):
            
        # Update the rest of the matrix
        # This routine creates a combination of the L and U matrices in one matrix (called LU here)
        # Then L and U are separated from LU
        pivot = LU[piv_col, piv_col]
        assert pivot != 0., "pivot is zero, can't continue"
        
        for row in range(piv_col + 1, n):
            multiplier = LU[row, piv_col] / pivot
            LU[row, piv_col] = multiplier
            LU[row, (piv_col+1):] -= multiplier * LU[piv_col, (piv_col+1):]
    # Separate L and U in the result
    # .triu() makes the lower-triangle half of a matrix all zeros
    U = np.triu(LU)
    L = LU - U + np.eye(n)
        
    return (L, U)

#### Let's try it...

In [7]:
A = np.array([
    [ 2. ,  7. ,  1. ,  8. ],
    [ 1. ,  5.5,  8.5,  5. ],
    [ 0. ,  1. , 12. ,  2.5],
    [-1. , -4.5, -4.5,  3.5]])

#Alternative to try:
#A = np.array([[1, 2, 3], [1,1,1], [-1,1,2]])

L,U = LUfactorNoPiv(A)
print("\nA\n", A, "\n\nL\n", L, "\n\nU\n", U)


A
 [[ 2.   7.   1.   8. ]
 [ 1.   5.5  8.5  5. ]
 [ 0.   1.  12.   2.5]
 [-1.  -4.5 -4.5  3.5]] 

L
 [[ 1.   0.   0.   0. ]
 [ 0.5  1.   0.   0. ]
 [ 0.   0.5  1.   0. ]
 [-0.5 -0.5  0.   1. ]] 

U
 [[2. 7. 1. 8.]
 [0. 2. 8. 1.]
 [0. 0. 8. 2.]
 [0. 0. 0. 8.]]


*Note how the results of the 4x4 compare perfectly to the manual calculation we had done earlier in lecture.*

***But will this work on ANY square matrix!!??? (nope - we'll see that in the next lecture!)***