# SPDs and Cholesky Matrix Factorization


### We'll start off by importing numpy and the linear algebra class (linalg) from numpy

In [1]:
import numpy as np
import numpy.linalg as npla

## Eigenvalues and Eigenvectors

In [27]:
#Examples of M to try:

#M = np.array([[1, 0], [0, 2]])
#M = np.array([[-1, 4], [5, -2]])
#M = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
#M = np.array([[1, 2, -1], [1, 1, 1], [0, 3, 4]])
#M = np.array([[1, -1], [1, 1]])

M= np.array( [ [4,-1],[-1,3] ])

d, V = npla.eig(M)
print('Eigenvalues:', d, '\n')
print('Eigenvectors:\n', V)

Eigenvalues: [4.61803399 2.38196601] 

Eigenvectors:
 [[ 0.85065081  0.52573111]
 [-0.52573111  0.85065081]]


**Symmetrical Positive Definite Matrices**

***How to define SPDs? They are SYMMETRICAL and they are POSITIVE DEFINITE.***

### Test A: Is the matrix C symmetrical?

In [22]:
C = np.array([[5, 5, 5],[5, 6, 5],[5, 5, 8]])

print("C:\n", C)
print("\nC.T:\n", C.T)

C:
 [[5 5 5]
 [5 6 5]
 [5 5 8]]

C.T:
 [[5 5 5]
 [5 6 5]
 [5 5 8]]


### Prove that C is equal to C.T:

In [8]:
# Calculation method to show equality:

print(C == C.T)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Imagine that C is a much bigger matrix - the above form is not convenient!**

In [20]:
# Another way to show this (gives True only if **every** entry is True in matrix):

print(np.all(C == C.T))
#print(np.any(C != C.T) == False)

if np.all(C == C.T):
    print("They're symmetrical, baby!")

True
They're symmetrical, baby!


### Test B: Is the matrix C Pos.Def?

*If so, then X.T @ C @ X should always be a positive number for **every** non-zero X vector*

In [23]:
# Choose any vector x that isn't a zero vector:
print(C)

x = np.array([11, 52, -55])
print("\nxT@C@x:\n", x.T@C@x)

[[5 5 5]
 [5 6 5]
 [5 5 8]]

xT@C@x:
 12099


**Note that this is just true for ONE vector x**

***You'd have to do this for ALL x to establish proof...
This is why it is easier to prove SPD using the easier route (see next example)***





\
Note on ***finding eigenvalues in numpy --- IMPORTANT! READ THIS!!!***

***npla.eig(C)[0]*** *gives you the eigenvalues in a vector,*

***npla.eig(C)[1]*** *gives you the eigenvectors (each column is an eigvector)*

In [24]:
lambdas = npla.eig(C)
print("Eigenvalues:\n", lambdas[0])
print()
print("Eigenvectors:\n", lambdas[1])

Eigenvalues:
 [16.43991452  0.42793012  2.13215536]

Eigenvectors:
 [[ 0.5248649   0.79374028 -0.30739746]
 [ 0.55885893 -0.59374805 -0.57891273]
 [ 0.64202299 -0.13205916  0.75522636]]


In [25]:
# Are the eigenvalues all >0 ??

print(npla.eig(C)[0] > 0)

[ True  True  True]


In [26]:
# Another way to show ALL eigenvalues are positive:

print(np.all(npla.eig(C)[0] > 0))

True


## Cholesky Factorization Example

In [29]:
# C is thus SPD
# Which means, we can do the Cholesky Factorization on it
# i.e. C = R@R.T

R = npla.cholesky(C)

print("C:\n", C)
print("R:\n",R,"\n")
print("Check the calculation: R@R.T:\n", R @ R.T)

C:
 [[5 5 5]
 [5 6 5]
 [5 5 8]]
R:
 [[ 2.23606798e+00  0.00000000e+00  0.00000000e+00]
 [ 2.23606798e+00  1.00000000e+00  0.00000000e+00]
 [ 2.23606798e+00 -4.85863154e-16  1.73205081e+00]] 

Check the calculation: R@R.T:
 [[5. 5. 5.]
 [5. 6. 5.]
 [5. 5. 8.]]


**Is that the SAME as the original matrix C?**

## Error Calculations

In [33]:
print("Residual:\n", C - R@R.T)  

print("\nResidual norm:", npla.norm(C - R@R.T))

print("\nRelative residual norm:", npla.norm(C - R@R.T) / npla.norm(C) )

Residual:
 [[-8.8817842e-16 -8.8817842e-16 -8.8817842e-16]
 [-8.8817842e-16 -8.8817842e-16  0.0000000e+00]
 [-8.8817842e-16  0.0000000e+00  0.0000000e+00]]

Residual norm: 2.175583928816829e-15

Relative residual norm: 1.3119264712386714e-16
