In [10]:
import numpy as np 
A = np.array([[1,0,1],[0,1,1],[1,1,1]])
print((A == 0) + (A == 1))


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [12]:
from scipy import sparse
A_sparse = sparse.csr_matrix(A)
print(type(A_sparse))
assert type(A_sparse) == sparse._csr.csr_matrix, not sparse

<class 'scipy.sparse._csr.csr_matrix'>


In [23]:
print(A_sparse)
print(A @ A)
print(A_sparse.mean(0))
print(A_sparse @ A)

  (0, 0)	1
  (0, 2)	1
  (1, 1)	1
  (1, 2)	1
  (2, 0)	1
  (2, 1)	1
  (2, 2)	1
[[2 1 2]
 [1 2 2]
 [2 2 3]]
[[0.66666667 0.66666667 1.        ]]
[[2 1 2]
 [1 2 2]
 [2 2 3]]


In [20]:
v = np.ones(4)
n = 4
print(v)
SV = v * np.ones((n,n))/n

print()
print(SV)

[1. 1. 1. 1.]

[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
