In [21]:
import numpy as np 
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
P = np.array([[0,1,0],[1,0,0],[0,0,1]])
print(P @ A)
print(A @ P)

[[4 5 6]
 [1 2 3]
 [7 8 9]]
[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [2]:
import numpy as np 
A = np.array([[1,2,3],[2,4,5],[3,5,6]])
B = np.array([[7,8,9],[8,10,11],[9,11,12]])
print(A @ B)
print(B @ A)

[[ 50  61  67]
 [ 91 111 122]
 [115 140 154]]
[[ 50  91 115]
 [ 61 111 140]
 [ 67 122 154]]


In [2]:
import numpy as np 
M = np.array([['a','b','c'], ['d','e','f'], ['g','h','i']])
M_t = M.T
print(M)
print(M_t)

[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]
[['a' 'd' 'g']
 ['b' 'e' 'h']
 ['c' 'f' 'i']]


In [ ]:
import numpy as np
A = np.array([[1,2,3],[2,5,6],[7]])

In [9]:
import numpy as np 
A = np.array([[5,3,3],[3,5,3],[3,3,5]])
U = np.array([[5,3,3],[0,3.2,1.2],[0,0,11/4]])
L = np.array([[1,0,0],[3/5,1,0],[3/5,3/8,1]])
print(L @ U)

[[5. 3. 3.]
 [3. 5. 3.]
 [3. 3. 5.]]
