In [1]:
print("hello world")

hello world


In [7]:
import numpy as np
a = np.matrix('3,-1,2; 0,1,2 ; 1,0,-1')
a_t = a.T
print(a)
print(a_t)


[[ 3 -1  2]
 [ 0  1  2]
 [ 1  0 -1]]
[[ 3  0  1]
 [-1  1  0]
 [ 2  2 -1]]


In [1]:
import numpy as np
a = np.matrix('1,2,3;4,5,6;7,8,9')
p = np.matrix('0,1,0;1,0,0;0,0,1')
print(a@p)
print(p@a)

[[2 1 3]
 [5 4 6]
 [8 7 9]]
[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [3]:
import numpy as np 
a = np.matrix('3,-1,2; 0,1,2 ; 1,0,-1')
a_2 = a @ a
print(a_2)

[[11 -4  2]
 [ 2  1  0]
 [ 2 -1  3]]


In [6]:
import numpy as np
a = np.matrix('3,-1,2; 0,1,2 ; 1,0,-1')
a_t = a.T
a_ta = a_t @ a
print(a_ta)

[[10 -3  5]
 [-3  2  0]
 [ 5  0  9]]


In [12]:
import numpy as np 
A = np.array([[2,-3,1],[0,2,3],[1,0,1]])
b = np.array([[1],[7],[4]])
print(A)
print(b)

[[ 2 -3  1]
 [ 0  2  3]
 [ 1  0  1]]
[[1]
 [7]
 [4]]


In [3]:
import numpy as np 
A = np.array([[2,-3,1],[0,2,3],[1,0,1]])
b = np.array([[1],[7],[4]])
print(A)
print(b)

[[ 2 -3  1]
 [ 0  2  3]
 [ 1  0  1]]
[[1]
 [7]
 [4]]


In [1]:
import numpy as np 
import numpy.linalg as npla
A = np.array([[2,-3,1],[0,2,3],[1,0,1]])
b = np.array([[1],[7],[4]])
x = npla.solve(A,b)
print(x)    

[[3.]
 [2.]
 [1.]]
