In [20]:
import numpy as np 
import numpy.linalg as npla 

import scipy 
from scipy import sparse

In [21]:
A = np.array([[4,-1,-1],[-2,6,1],[-1,1,7]])
b = np.array([3,9,-6])
xideal  = np.array([1,2,-1])

In [22]:
m,n = A.shape 
d = A.diagonal()

#.diag is used to turn the diagonals vectorinto the diagonal matrix D 
#way to turn vector of a n x 1 size to n x n matrix
D = np.diag(d)

C = A - D
print("c = \n", C, "\n")

#function to make a vector with size n x 1by n matrix with all zeros 
x = np.zeros(n)


c = 
 [[ 0 -1 -1]
 [-2  0  1]
 [-1  1  0]] 



In [32]:
xnew = (b -C@x)/d
print("x[1] = ", xnew)

#following lines only if x solution is known 
relres = npla.norm(xnew - xideal) / npla.norm(xideal)
error = npla.norm(xnew-xideal)
print("error: ", error, "\nrelres:", relres)

#otherwise would use 
error = npla.norm(A @ xnew - b) #ideally would be 0 if xnew is = x 
print("error: ", error)
relres = npla.norm(A @ xnew - b)/npla.norm(b)
print("relres: ", relres)


x[1] =  [ 0.99913448  1.99972668 -0.99968112]
error:  0.00096204045562781 
relres: 0.0003927513713671293
error:  0.004522016940133963
relres:  0.0004028532877897414


In [38]:
x = [0,0,0]
for i in range(70):
    #print("b-C@x: ", b - C@x)
    #print("d: ", d)
    xnew = (b -C@x)/d
    print("x[", i, "] = ", xnew, end = " ")

    #relres = npla.norm(xnew - xideal) / npla.norm(xideal)
    error = npla.norm(xnew-xideal)
    print("error: ", error)
    #print("\nrelres:", relres)
    x = xnew
    if error <= 1e-8:
        break 

x[ 0 ] =  [ 0.75        1.5        -0.85714286] error:  0.576981943621554
x[ 1 ] =  [ 0.91071429  1.89285714 -0.96428571] error:  0.14396888836247398
x[ 2 ] =  [ 0.98214286  1.96428571 -0.99744898] error:  0.04001119168713812
x[ 3 ] =  [ 0.99170918  1.99362245 -0.99744898] error:  0.010766545290901954
x[ 4 ] =  [ 0.99904337  1.99681122 -1.00027332] error:  0.0033403803804333615
x[ 5 ] =  [ 0.99913448  1.99972668 -0.99968112] error:  0.00096204045562781
x[ 6 ] =  [ 1.00001139  1.99965835 -1.0000846 ] error:  0.0003521572036386853
x[ 7 ] =  [ 0.99989344  2.0000179  -0.99994957] error:  0.00011924659362186495
x[ 8 ] =  [ 1.00001708  1.99995607 -1.00001778] error:  5.037389589454705e-05
x[ 9 ] =  [ 0.99998457  2.00000866 -0.99999128] error:  1.9720575687738536e-05
x[ 10 ] =  [ 1.00000434  1.99999341 -1.00000344] error:  8.613617664489088e-06
x[ 11 ] =  [ 0.99999749  2.00000202 -0.99999844] error:  3.580699901177801e-06
x[ 12 ] =  [ 1.0000009   1.9999989  -1.00000065] error:  1.557028062801

When Jacobi method does not always converge

In [56]:
A = np.array([[1,2],[3,4]])
b = np.array([3,7])
xideal = np.array([1,1])

d = A.diagonal()
D = np.diag(d)
C = A-D

m = npla.pinv(D)@C
evs = npla.eig(m)[0]
print(evs)
print(A[0][0])
m,n = A.shape
print(m)
print(n)
s = 0
for i in range(m):
    for j in range(n):
        print(i)
        print(j)
        if i == j:
            dia = A[i][j]
        else:
            s += A[i][j]
    if dia < s:
        print("not diag dominant")
    s = 0 
x = np.array([0,0])
for i in range(70):
    #print("b-C@x: ", b - C@x)
    #print("d: ", d)
    xnew = (b -C@x)/d
    print("x[", i, "] = ", xnew, end = " ")

    #relres = npla.norm(xnew - xideal) / npla.norm(xideal)
    error = npla.norm(xnew-xideal)
    print("error: ", error)
    #print("\nrelres:", relres)
    x = xnew
    if error <= 1e-8:
        break 

[ 1.22474487 -1.22474487]
1
2
2
0
0
0
1
not diag dominant
1
0
1
1
x[ 0 ] =  [3.   1.75] error:  2.1360009363293826
x[ 1 ] =  [-0.5 -0.5] error:  2.1213203435596424
x[ 2 ] =  [4.    2.125] error:  3.204001404494074
x[ 3 ] =  [-1.25 -1.25] error:  3.181980515339464
x[ 4 ] =  [5.5    2.6875] error:  4.806002106741111
x[ 5 ] =  [-2.375 -2.375] error:  4.772970773009196
x[ 6 ] =  [7.75    3.53125] error:  7.209003160111667
x[ 7 ] =  [-4.0625 -4.0625] error:  7.159456159513794
x[ 8 ] =  [11.125     4.796875] error:  10.8135047401675
x[ 9 ] =  [-6.59375 -6.59375] error:  10.73918423927069
x[ 10 ] =  [16.1875     6.6953125] error:  16.22025711025125
x[ 11 ] =  [-10.390625 -10.390625] error:  16.108776358906034
x[ 12 ] =  [23.78125     9.54296875] error:  24.330385665376877
x[ 13 ] =  [-16.0859375 -16.0859375] error:  24.163164538359055
x[ 14 ] =  [35.171875   13.81445312] error:  36.49557849806531
x[ 15 ] =  [-24.62890625 -24.62890625] error:  36.24474680753858
x[ 16 ] =  [52.2578125  20.22167